/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utility;

/**
 *
 * @author akshos
 */
public class Wait extends javax.swing.JInternalFrame {

    /**
     * Creates new form Wait
     */
    public Wait() {
        initComponents();
    }
    
    public void closeWait(){
        this.doDefaultCloseAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waitLabel = new javax.swing.JLabel();

        waitLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        waitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waitLabel.setText("PLEASE WAIT");
        getContentPane().add(waitLabel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel waitLabel;
    // End of variables declaration//GEN-END:variables
}
