/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fain;

/**
 *
 * @author Another
 */
public class A_transaction extends javax.swing.JInternalFrame {

    /**
     * Creates new form A_transaction
     */
    public A_transaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateTbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        branchTbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        debitTbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        creditTbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        amountTbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        narrationTbox = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        headButton = new javax.swing.JButton();

        setTitle("Transactions Data Entry");

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 20, 20));

        jLabel1.setText("Date");
        jPanel1.add(jLabel1);
        jPanel1.add(dateTbox);

        jLabel2.setText("Branch");
        jPanel1.add(jLabel2);
        jPanel1.add(branchTbox);

        jLabel3.setText("Debit ( R )");
        jPanel1.add(jLabel3);
        jPanel1.add(debitTbox);

        jLabel4.setText("Credit ( P )");
        jPanel1.add(jLabel4);
        jPanel1.add(creditTbox);

        jLabel5.setText("Amount");
        jPanel1.add(jLabel5);
        jPanel1.add(amountTbox);

        jLabel6.setText("Narration");
        jPanel1.add(jLabel6);
        jPanel1.add(narrationTbox);

        exitButton.setText("Esc : Exit");
        jPanel1.add(exitButton);

        headButton.setText("F10 : A/c Head");
        jPanel1.add(headButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTbox;
    private javax.swing.JTextField branchTbox;
    private javax.swing.JTextField creditTbox;
    private javax.swing.JTextField dateTbox;
    private javax.swing.JTextField debitTbox;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton headButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField narrationTbox;
    // End of variables declaration//GEN-END:variables
}
