/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fain;
import database.DBConnection;
import database.MasterDB;
import database.StockDB;
import java.sql.Statement;
import utility.Codes;
/**
/**
 *
 * @author akshos
 */
public class AStock extends javax.swing.JInternalFrame implements RefreshOption{
DBConnection dbConnection;
    /**
     * Creates new form MasterEntry
     */
    public AStock() {
        initComponents();
    }
    public AStock(DBConnection db, int mode, String id){
        this.dbConnection = db;
        initComponents();
        if(mode == Codes.EDIT){
            refreshContents(Codes.REFRESH_ALL);
        }
    }
    
    private void insertData(){
        Statement stmt=dbConnection.getStatement();
        String icode        =itemCodeTbox.getText();
        String iname        =itemNameTbox.getText();
        int currentStock    =Integer.parseInt(currentStockTbox.getText());
        double rate         =Double.parseDouble(rateTbox.getText());
        String purchase     ="";
        Object selectedItem = purchasesCbox.getSelectedItem();
        if (selectedItem != null)
        {
            purchase = selectedItem.toString();
        }      
        String sales     ="";
         selectedItem = salesCbox.getSelectedItem();
        if (selectedItem != null)
        {
            sales = selectedItem.toString();
        }
        String stock     ="";
         selectedItem = stockCbox.getSelectedItem();
        if (selectedItem != null)
        {
            stock = selectedItem.toString();
        }
        StockDB.insert(stmt, icode, iname, currentStock, rate, purchase, sales, stock);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outerPanel = new javax.swing.JPanel();
        leftInerPannel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelsPanel = new javax.swing.JPanel();
        itemCodeLabel = new javax.swing.JLabel();
        itemNameLabel = new javax.swing.JLabel();
        currentStockLabel = new javax.swing.JLabel();
        rateLabel = new javax.swing.JLabel();
        purchasesLabel = new javax.swing.JLabel();
        SalesLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        rightInerPannel = new javax.swing.JPanel();
        itemCodeTbox = new javax.swing.JTextField();
        itemNameTbox = new javax.swing.JTextField();
        currentStockTbox = new javax.swing.JTextField();
        rateTbox = new javax.swing.JTextField();
        purchasesCbox = new javax.swing.JComboBox<>();
        salesCbox = new javax.swing.JComboBox<>();
        stockCbox = new javax.swing.JComboBox<>();
        buttonPanel = new javax.swing.JPanel();
        enterButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("Data Entry (Stock)");
        setPreferredSize(new java.awt.Dimension(450, 410));

        outerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        outerPanel.setLayout(new java.awt.GridLayout(1, 2));

        leftInerPannel.setLayout(new java.awt.GridLayout(1, 2));

        logoPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fain/note.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        leftInerPannel.add(logoPanel);

        labelsPanel.setLayout(new java.awt.GridLayout(8, 0, 0, 10));

        itemCodeLabel.setText("Item Code");
        labelsPanel.add(itemCodeLabel);

        itemNameLabel.setText("Item Name");
        labelsPanel.add(itemNameLabel);

        currentStockLabel.setText("Current Stock");
        labelsPanel.add(currentStockLabel);

        rateLabel.setText("Rate");
        labelsPanel.add(rateLabel);

        purchasesLabel.setText("Purchases A/c");
        labelsPanel.add(purchasesLabel);

        SalesLabel.setText("Sales A/c");
        labelsPanel.add(SalesLabel);

        stockLabel.setText("Stock A/c");
        labelsPanel.add(stockLabel);

        leftInerPannel.add(labelsPanel);

        outerPanel.add(leftInerPannel);

        rightInerPannel.setLayout(new java.awt.GridLayout(8, 0, 0, 10));

        itemCodeTbox.setText("jTextField1");
        itemCodeTbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeTboxActionPerformed(evt);
            }
        });
        rightInerPannel.add(itemCodeTbox);

        itemNameTbox.setText("jTextField2");
        rightInerPannel.add(itemNameTbox);

        currentStockTbox.setText("jTextField3");
        rightInerPannel.add(currentStockTbox);

        rateTbox.setText("jTextField4");
        rightInerPannel.add(rateTbox);

        purchasesCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rightInerPannel.add(purchasesCbox);

        salesCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rightInerPannel.add(salesCbox);

        stockCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rightInerPannel.add(stockCbox);

        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 60, 2, 60));
        buttonPanel.setLayout(new java.awt.BorderLayout());

        enterButton.setText("ENTER");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(enterButton, java.awt.BorderLayout.CENTER);

        rightInerPannel.add(buttonPanel);

        outerPanel.add(rightInerPannel);

        getContentPane().add(outerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCodeTboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeTboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCodeTboxActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
        insertData();
    }//GEN-LAST:event_enterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SalesLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel currentStockLabel;
    private javax.swing.JTextField currentStockTbox;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel itemCodeLabel;
    private javax.swing.JTextField itemCodeTbox;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JTextField itemNameTbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel labelsPanel;
    private javax.swing.JPanel leftInerPannel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel outerPanel;
    private javax.swing.JComboBox<String> purchasesCbox;
    private javax.swing.JLabel purchasesLabel;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JTextField rateTbox;
    private javax.swing.JPanel rightInerPannel;
    private javax.swing.JComboBox<String> salesCbox;
    private javax.swing.JComboBox<String> stockCbox;
    private javax.swing.JLabel stockLabel;
    // End of variables declaration//GEN-END:variables

    public void refreshContents(int REFRESH_ALL) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
