/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fain;

import database.BarrelDB;
import database.DBConnection;
import database.BranchDB;
import database.CompanyBarrelDB;
import database.CustomerDB;
import database.TransactionDB;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import utility.Codes;
import utility.UtilityFuncs;

/**
 *
 * @author akshos
 */
public class BarrelSummary extends javax.swing.JInternalFrame implements RefreshOption{
    DBConnection dbConnection;
    Main mainFrame;
    int level;
    /**
     * Creates new form EMaster
     */
    public BarrelSummary(DBConnection db, Main frame, int level) {
        this.dbConnection = db;
        this.mainFrame = frame;
        this.level = level;
        initComponents();
        updateTable();
        this.dataTable.requestFocus();
        loadBarrelSummary();
    }
    
    private void loadBarrelSummary(){
        int companyOpStock = CompanyBarrelDB.getCompanyOpStock(dbConnection.getStatement());
        int companyTotalIssued = CompanyBarrelDB.getTotalIssued(dbConnection.getStatement());
        int companyTotalLifted = CompanyBarrelDB.getTotalLifted(dbConnection.getStatement());
        
        
        int companyBarrels = companyOpStock + companyTotalIssued - companyTotalLifted;
        this.companyBarrelsTbox.setText(String.valueOf(companyBarrels));
        
        int companyShortage = CompanyBarrelDB.getCompanyShortage(dbConnection.getStatement());
        this.companyShortageTbox.setText(String.valueOf(companyShortage));
        
        //net number of barrels from company currently at hand/at customer
        companyBarrels = companyBarrels - companyShortage;
        this.companyTotalTbox.setText(String.valueOf(companyBarrels));
        
        int customerTotalIssued = BarrelDB.getTotalIssued(dbConnection.getStatement());
        int customerTotalLifted = BarrelDB.getTotalLifted(dbConnection.getStatement());
        
        //get current number of issued barrels
        int customerIssued = customerTotalIssued - customerTotalLifted;
        //get the current number of latex barrels at hand
        int latexBarrels = customerTotalLifted - companyTotalLifted;
        //get the current number of empty barrels at hand
        int emptyBarrels = companyBarrels - (customerIssued + latexBarrels);
        
        this.customerTotalIssuedTbox.setText(String.valueOf(customerIssued));
        this.customerLatexBarrelTbox.setText(String.valueOf(latexBarrels));
        this.emptyBarrelsTbox.setText(String.valueOf(emptyBarrels));
        this.customerTotalTbox.setText(String.valueOf(customerIssued + latexBarrels + emptyBarrels));
    }
    
    private void saveCompanyShortage(){
        String shortage = this.companyShortageTbox.getText();
        CompanyBarrelDB.setCompanyShortage(dbConnection.getStatement(), shortage);
    }
    
    private void setMinWidth(){
        TableColumnModel col = this.dataTable.getColumnModel();
        int n = this.dataTable.getColumnCount();
        for(int i = 0; i < n; i++){
            col.getColumn(i).setMinWidth(100);
        }
        this.dataTable.setRowHeight(30);
    }
    
    private void setColumnAlignment(){
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        int[] centerIndex = {0, 3};
        for( int i = 0; i < centerIndex.length; i++){
            this.dataTable.getColumnModel().getColumn(centerIndex[i]).setCellRenderer(centerRenderer);
        }
    }
    
    private void resizeColumns(){
        int screenWidth = this.getWidth();
        int colCount = this.dataTable.getColumnCount();
        if(colCount == 0) return;
        int colWidth  = (screenWidth / (colCount-1)) - (100/(colCount)+10);
        if(colWidth > 100){
            TableColumnModel col = this.dataTable.getColumnModel();
            for(int i = 1; i < colCount; i++){
                col.getColumn(i).setPreferredWidth(colWidth);
            }
        }
    }
    
    public void updateTable(){
        TableModel table = BarrelDB.getBarrelSummary(dbConnection.getStatement());
        this.dataTable.setModel(table);
        UtilityFuncs.setTableFont(dataTable);
        setMinWidth();
        resizeColumns();
        setColumnAlignment();
    }
    

    public void refreshContents(int code){
        if(code == Codes.REFRESH_BARREL){
            updateTable();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        lowerPanel = new javax.swing.JPanel();
        findButton = new javax.swing.JButton();
        topButton = new javax.swing.JButton();
        bottomButton = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        summaryPanel = new javax.swing.JPanel();
        businessPanel = new javax.swing.JPanel();
        businessAccountLabel = new javax.swing.JLabel();
        businessSummaryPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        spacerPanel1 = new javax.swing.JPanel();
        labelPanel = new javax.swing.JPanel();
        businessTotelLabel = new javax.swing.JLabel();
        businessShortageLabel = new javax.swing.JLabel();
        businessTotalLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        companyBarrelsTbox = new javax.swing.JTextField();
        spacesLabel1 = new javax.swing.JLabel();
        companyShortageTbox = new javax.swing.JTextField();
        spacesLabel2 = new javax.swing.JLabel();
        companyTotalTbox = new javax.swing.JTextField();
        customerPanel = new javax.swing.JPanel();
        customerAccountPanel = new javax.swing.JLabel();
        customerSummaryPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        spacerPanel2 = new javax.swing.JPanel();
        labelPanel2 = new javax.swing.JPanel();
        customerTotalIssuesLabel = new javax.swing.JLabel();
        customerLatexBarrelLabel = new javax.swing.JLabel();
        emptyBarrelLabel = new javax.swing.JLabel();
        customerTotalLabel = new javax.swing.JLabel();
        inputPanel2 = new javax.swing.JPanel();
        customerTotalIssuedTbox = new javax.swing.JTextField();
        spacerLabel4 = new javax.swing.JLabel();
        customerLatexBarrelTbox = new javax.swing.JTextField();
        spacerLabel5 = new javax.swing.JLabel();
        emptyBarrelsTbox = new javax.swing.JTextField();
        spacerLabel6 = new javax.swing.JLabel();
        customerTotalTbox = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Barrel Summary");
        setMinimumSize(new java.awt.Dimension(785, 450));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        upperPanel.setLayout(new java.awt.BorderLayout());

        tableScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        tableScrollPane.setAutoscrolls(true);
        tableScrollPane.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tableScrollPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });

        dataTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dataTable.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Code", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dataTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dataTableKeyPressed(evt);
            }
        });
        tableScrollPane.setViewportView(dataTable);

        upperPanel.add(tableScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(upperPanel, java.awt.BorderLayout.CENTER);

        lowerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        lowerPanel.setPreferredSize(new java.awt.Dimension(639, 50));
        lowerPanel.setLayout(new java.awt.GridLayout(1, 6, 20, 0));

        findButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        findButton.setText("F5: Find");
        findButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });
        lowerPanel.add(findButton);

        topButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        topButton.setText("F6: Top");
        topButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });
        lowerPanel.add(topButton);

        bottomButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bottomButton.setText("F7: Bottom");
        bottomButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });
        lowerPanel.add(bottomButton);

        getContentPane().add(lowerPanel, java.awt.BorderLayout.SOUTH);

        titlePanel.setPreferredSize(new java.awt.Dimension(248, 200));
        titlePanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("BARREL SUMMARY");
        titlePanel.add(titleLabel, java.awt.BorderLayout.NORTH);

        summaryPanel.setLayout(new java.awt.GridLayout(1, 2));

        businessPanel.setLayout(new java.awt.BorderLayout());

        businessAccountLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        businessAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        businessAccountLabel.setText("BUSINESS ACCOUNT");
        businessAccountLabel.setPreferredSize(new java.awt.Dimension(137, 30));
        businessPanel.add(businessAccountLabel, java.awt.BorderLayout.PAGE_START);

        businessSummaryPanel.setLayout(new java.awt.GridLayout(1, 2, 0, 10));

        leftPanel.setLayout(new java.awt.GridLayout(1, 2));

        spacerPanel1.setLayout(new java.awt.GridLayout(3, 0, 50, 10));
        leftPanel.add(spacerPanel1);

        labelPanel.setLayout(new java.awt.GridLayout(3, 0));

        businessTotelLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        businessTotelLabel.setText("COMPANY:");
        businessTotelLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        labelPanel.add(businessTotelLabel);

        businessShortageLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        businessShortageLabel.setText("SHORTAGE :");
        businessShortageLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        labelPanel.add(businessShortageLabel);

        businessTotalLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        businessTotalLabel.setText("TOTAL :");
        businessTotalLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        labelPanel.add(businessTotalLabel);

        leftPanel.add(labelPanel);

        businessSummaryPanel.add(leftPanel);

        inputPanel.setLayout(new java.awt.GridLayout(3, 2, 0, 10));

        companyBarrelsTbox.setEditable(false);
        companyBarrelsTbox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        companyBarrelsTbox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        companyBarrelsTbox.setRequestFocusEnabled(false);
        companyBarrelsTbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                companyBarrelsTboxFocusLost(evt);
            }
        });
        companyBarrelsTbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });
        inputPanel.add(companyBarrelsTbox);
        inputPanel.add(spacesLabel1);

        companyShortageTbox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        companyShortageTbox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        companyShortageTbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                companyShortageTboxFocusLost(evt);
            }
        });
        companyShortageTbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });
        inputPanel.add(companyShortageTbox);
        inputPanel.add(spacesLabel2);

        companyTotalTbox.setEditable(false);
        companyTotalTbox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        companyTotalTbox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        companyTotalTbox.setRequestFocusEnabled(false);
        companyTotalTbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });
        inputPanel.add(companyTotalTbox);

        businessSummaryPanel.add(inputPanel);

        businessPanel.add(businessSummaryPanel, java.awt.BorderLayout.CENTER);

        summaryPanel.add(businessPanel);

        customerPanel.setLayout(new java.awt.BorderLayout());

        customerAccountPanel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        customerAccountPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerAccountPanel.setText("CUSTOMER ACCOUNT");
        customerAccountPanel.setPreferredSize(new java.awt.Dimension(137, 30));
        customerPanel.add(customerAccountPanel, java.awt.BorderLayout.PAGE_START);

        customerSummaryPanel.setLayout(new java.awt.GridLayout(1, 2));

        rightPanel.setLayout(new java.awt.GridLayout(1, 2));
        rightPanel.add(spacerPanel2);

        labelPanel2.setLayout(new java.awt.GridLayout(4, 0));

        customerTotalIssuesLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        customerTotalIssuesLabel.setText("ISSUED :");
        customerTotalIssuesLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        labelPanel2.add(customerTotalIssuesLabel);

        customerLatexBarrelLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        customerLatexBarrelLabel.setText("LATEX BARREL :");
        customerLatexBarrelLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        labelPanel2.add(customerLatexBarrelLabel);

        emptyBarrelLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emptyBarrelLabel.setText("EMPTY BARREL :");
        emptyBarrelLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        labelPanel2.add(emptyBarrelLabel);

        customerTotalLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        customerTotalLabel.setText("TOTAL :");
        customerTotalLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        labelPanel2.add(customerTotalLabel);

        rightPanel.add(labelPanel2);

        customerSummaryPanel.add(rightPanel);

        inputPanel2.setLayout(new java.awt.GridLayout(4, 2, 0, 4));

        customerTotalIssuedTbox.setEditable(false);
        customerTotalIssuedTbox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        customerTotalIssuedTbox.setRequestFocusEnabled(false);
        customerTotalIssuedTbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });
        inputPanel2.add(customerTotalIssuedTbox);
        inputPanel2.add(spacerLabel4);

        customerLatexBarrelTbox.setEditable(false);
        customerLatexBarrelTbox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        customerLatexBarrelTbox.setRequestFocusEnabled(false);
        customerLatexBarrelTbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });
        inputPanel2.add(customerLatexBarrelTbox);
        inputPanel2.add(spacerLabel5);

        emptyBarrelsTbox.setEditable(false);
        emptyBarrelsTbox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emptyBarrelsTbox.setRequestFocusEnabled(false);
        emptyBarrelsTbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });
        inputPanel2.add(emptyBarrelsTbox);
        inputPanel2.add(spacerLabel6);

        customerTotalTbox.setEditable(false);
        customerTotalTbox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        customerTotalTbox.setRequestFocusEnabled(false);
        customerTotalTbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });
        inputPanel2.add(customerTotalTbox);

        customerSummaryPanel.add(inputPanel2);

        customerPanel.add(customerSummaryPanel, java.awt.BorderLayout.CENTER);

        summaryPanel.add(customerPanel);

        titlePanel.add(summaryPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(titlePanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        Preferences.storeInternalFrameDimension(this);
    }//GEN-LAST:event_formInternalFrameClosing

    private void dataTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataTableKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_R){
            this.updateTable();
        }
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_F5){
        
        }
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_F6){
            this.dataTable.setRowSelectionInterval(0, 0);
        }
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_F7){
            int lastRowIndex = this.dataTable.getRowCount() - 1;
            this.dataTable.setRowSelectionInterval(lastRowIndex, lastRowIndex);
        }
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE){
            this.doDefaultCloseAction();
        }else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP){
            if(this.dataTable.getSelectedRow() == 0){
                this.companyShortageTbox.requestFocus();
            }
        }
    }//GEN-LAST:event_dataTableKeyPressed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        resizeColumns();
    }//GEN-LAST:event_formComponentResized

    private void keyPressedHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressedHandler
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE){
            this.doDefaultCloseAction();
        }else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            javax.swing.JComponent cmp = (javax.swing.JComponent)evt.getSource();
            cmp.transferFocus();
        }else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP){
            javax.swing.JComponent cmp = (javax.swing.JComponent)evt.getSource();
            cmp.transferFocusBackward();
        }else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN){
            javax.swing.JComponent cmp = (javax.swing.JComponent)evt.getSource();
            cmp.transferFocus();
        }
    }//GEN-LAST:event_keyPressedHandler

    private void companyBarrelsTboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyBarrelsTboxFocusLost

    }//GEN-LAST:event_companyBarrelsTboxFocusLost

    private void companyShortageTboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyShortageTboxFocusLost
        saveCompanyShortage();
    }//GEN-LAST:event_companyShortageTboxFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottomButton;
    private javax.swing.JLabel businessAccountLabel;
    private javax.swing.JPanel businessPanel;
    private javax.swing.JLabel businessShortageLabel;
    private javax.swing.JPanel businessSummaryPanel;
    private javax.swing.JLabel businessTotalLabel;
    private javax.swing.JLabel businessTotelLabel;
    private javax.swing.JTextField companyBarrelsTbox;
    private javax.swing.JTextField companyShortageTbox;
    private javax.swing.JTextField companyTotalTbox;
    private javax.swing.JLabel customerAccountPanel;
    private javax.swing.JLabel customerLatexBarrelLabel;
    private javax.swing.JTextField customerLatexBarrelTbox;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JPanel customerSummaryPanel;
    private javax.swing.JTextField customerTotalIssuedTbox;
    private javax.swing.JLabel customerTotalIssuesLabel;
    private javax.swing.JLabel customerTotalLabel;
    private javax.swing.JTextField customerTotalTbox;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel emptyBarrelLabel;
    private javax.swing.JTextField emptyBarrelsTbox;
    private javax.swing.JButton findButton;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JPanel inputPanel2;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JPanel labelPanel2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel lowerPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel spacerLabel4;
    private javax.swing.JLabel spacerLabel5;
    private javax.swing.JLabel spacerLabel6;
    private javax.swing.JPanel spacerPanel1;
    private javax.swing.JPanel spacerPanel2;
    private javax.swing.JLabel spacesLabel1;
    private javax.swing.JLabel spacesLabel2;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton topButton;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
