/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fain;

import database.UsersDB;
import javax.swing.JOptionPane;
import utility.Codes;
import users.User;

/**
 *
 * @author akshos
 */
public class CreateUser extends javax.swing.JInternalFrame {
    Main mainFrame;
    
    /** Creates new form createUser */
    public CreateUser() {
        initComponents();
    }
    
    public CreateUser(Main frame, int action, User user){
        initComponents();
        this.mainFrame = frame;
        initDetails(action, user);
    }
    
    public CreateUser(Main frame, int action){
        initComponents();
        this.mainFrame = frame;
        initDetails(action, null);
    }
    
    private void addUser(){
        String username = this.usernameTbox.getText();
        if(UsersDB.existingUser(username)){
            JOptionPane.showMessageDialog(this, "Username already exists", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String password = this.passwordPbox.getText();
        String rePassword = this.rePasswodPbox.getText();
        if(password.compareTo(rePassword) != 0){
            JOptionPane.showMessageDialog(this, "Passwords do not match", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        int type = Codes.STANDARD_USER;
        if(this.typeCbox.getSelectedItem().toString().compareTo("Administrator") == 0){
            type = Codes.ADMIN_USER;
        }
        UsersDB.addUser(username, password, type);
        mainFrame.initLogin();
        this.doDefaultCloseAction();
    }
    
    public void initDetails(int action, User user){
        if(action == Codes.CREARTE_ADMIN){
            this.headingLabel.setText("Create an Administrator Account");
            this.typeCbox.setSelectedIndex(0);
            this.typeCbox.setEditable(false);
            this.typeCbox.setEnabled(false);
            this.setClosable(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        detailsPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        iconPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        rPasswordLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        usernameTbox = new javax.swing.JTextField();
        passwordPbox = new javax.swing.JPasswordField();
        rePasswodPbox = new javax.swing.JPasswordField();
        typeCbox = new javax.swing.JComboBox<>();
        createButton = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(459, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        headingLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("Create User");
        headingLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(headingLabel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        detailsPanel.setLayout(new java.awt.GridLayout(1, 2));

        leftPanel.setLayout(new java.awt.GridLayout(1, 2));

        iconPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fain/user.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        iconPanel.add(jLabel2, java.awt.BorderLayout.CENTER);

        leftPanel.add(iconPanel);

        labelPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        labelPanel.setLayout(new java.awt.GridLayout(5, 0, 10, 0));

        usernameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usernameLabel.setText("Username");
        labelPanel.add(usernameLabel);

        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passwordLabel.setText("Password");
        labelPanel.add(passwordLabel);

        rPasswordLabel.setText("Retype Password");
        labelPanel.add(rPasswordLabel);

        typeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        typeLabel.setText("Type");
        labelPanel.add(typeLabel);

        leftPanel.add(labelPanel);

        detailsPanel.add(leftPanel);

        rightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 10, 10));
        rightPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 15));

        usernameTbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rightPanel.add(usernameTbox);

        passwordPbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordPboxFocusGained(evt);
            }
        });
        rightPanel.add(passwordPbox);

        rePasswodPbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rePasswodPboxFocusGained(evt);
            }
        });
        rightPanel.add(rePasswodPbox);

        typeCbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        typeCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Standard User" }));
        rightPanel.add(typeCbox);

        createButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        createButton.setText("CREATE");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        rightPanel.add(createButton);

        detailsPanel.add(rightPanel);

        getContentPane().add(detailsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordPboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordPboxFocusGained
        this.passwordPbox.selectAll();
    }//GEN-LAST:event_passwordPboxFocusGained

    private void rePasswodPboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rePasswodPboxFocusGained
        this.rePasswodPbox.selectAll();
    }//GEN-LAST:event_rePasswodPboxFocusGained

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        addUser();
    }//GEN-LAST:event_createButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPbox;
    private javax.swing.JLabel rPasswordLabel;
    private javax.swing.JPasswordField rePasswodPbox;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JComboBox<String> typeCbox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTbox;
    // End of variables declaration//GEN-END:variables

}
