/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fain;

import javax.swing.JOptionPane;
import users.User;
import utility.Codes;
/**
 *
 * @author akshos
 */
public class Login extends javax.swing.JInternalFrame {
    Main mainFrame;
    User user;
    int mode;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    public Login(Main frame, User user, int mode){
        initComponents();
        this.usernameLabel.setText("<html><b>Username :<b></html>");
        this.passwordLabel.setText("<html><b>Password :<b></html>");
        this.setSize(680, 340);
        this.mainFrame = frame;
        this.user = user;
        this.mode = mode;
        initMode();
    }
    
    private void initMode(){
        if(mode == Codes.LOGIN){
            
        }
    }
    
    private void validateUsername(){
        if(!User.validUsername(this.usernameTbox.getText())){
            this.usernameLabel.setText("<html><b>Username :<b> <span style=\"color:red\">invalid username</span></html>");
        }
        else{
            this.usernameLabel.setText("<html><b>Username :<b></html>");
        }
    }
    
    private void validatePassword(){
        if(!User.validUsername(this.passwordPbox.getText())){
            this.passwordLabel.setText("<html><b>Password :<b> <span style=\"color:red\">invalid password</span></html>");
        }
        else{
            this.passwordLabel.setText("<html><b>Password :<b></html>");
        }
    }
    
    private void exit(){
        this.mainFrame.closeFain();
        this.doDefaultCloseAction();
    }
    
    private void attemptLogin(){
        String username = this.usernameTbox.getText();
        String password = this.passwordPbox.getText();
        if(!User.validPassword(password) || !User.validUsername(username)){
            JOptionPane.showMessageDialog(this, "Please enter a valid uername and password", "Cannot Login", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        this.user = new User(username);
        if(user.authenticate(password) == Codes.AUTHORIZED){
            this.mainFrame.setUser(this.user);
            this.setVisible(false);
            this.mainFrame.loginSuccess();
            this.doDefaultCloseAction();
        }else{
            JOptionPane.showMessageDialog(this, "Username or Password incorrect", "Cannot Login", JOptionPane.WARNING_MESSAGE);
            this.user = null;
            return;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        iconPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        entryPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameTbox = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordPbox = new javax.swing.JPasswordField();
        buttonPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        labelPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();

        centerPanel.setLayout(new java.awt.BorderLayout());

        iconPanel.setPreferredSize(new java.awt.Dimension(170, 0));
        iconPanel.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fain/user100x100.png"))); // NOI18N
        iconPanel.add(jLabel3, java.awt.BorderLayout.CENTER);

        centerPanel.add(iconPanel, java.awt.BorderLayout.WEST);

        entryPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 10));
        entryPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 10));

        usernameLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        usernameLabel.setText("Username");
        usernameLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        entryPanel.add(usernameLabel);

        usernameTbox.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        usernameTbox.setToolTipText("Enter you username");
        usernameTbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTboxActionPerformed(evt);
            }
        });
        usernameTbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameTboxKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedHandler(evt);
            }
        });
        entryPanel.add(usernameTbox);

        passwordLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        passwordLabel.setText("Password");
        passwordLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        entryPanel.add(passwordLabel);

        passwordPbox.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        passwordPbox.setToolTipText("Enter your password");
        passwordPbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPboxActionPerformed(evt);
            }
        });
        passwordPbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordPboxKeyTyped(evt);
            }
        });
        entryPanel.add(passwordPbox);

        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        buttonPanel.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        loginButton.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginButtonKeyPressed(evt);
            }
        });
        buttonPanel.add(loginButton);

        exitButton.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(exitButton);

        entryPanel.add(buttonPanel);

        centerPanel.add(entryPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        labelPanel.setPreferredSize(new java.awt.Dimension(416, 50));
        labelPanel.setLayout(new java.awt.BorderLayout());

        loginLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("User Authentication");
        loginLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelPanel.add(loginLabel, java.awt.BorderLayout.CENTER);

        getContentPane().add(labelPanel, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTboxKeyTyped
        validateUsername();
    }//GEN-LAST:event_usernameTboxKeyTyped

    private void passwordPboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordPboxKeyTyped
        validatePassword();
    }//GEN-LAST:event_passwordPboxKeyTyped

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        attemptLogin();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        exit();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void usernameTboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTboxActionPerformed
        this.passwordPbox.requestFocus();
    }//GEN-LAST:event_usernameTboxActionPerformed

    private void passwordPboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPboxActionPerformed
        attemptLogin();
    }//GEN-LAST:event_passwordPboxActionPerformed

    private void loginButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginButtonKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE){
            exit();
        }else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            attemptLogin();
        }
    }//GEN-LAST:event_loginButtonKeyPressed

    private void keyPressedHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressedHandler
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE){
            exit();
        }else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            javax.swing.JComponent cmp = (javax.swing.JComponent)evt.getSource();
            cmp.transferFocus();
        }
    }//GEN-LAST:event_keyPressedHandler


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel entryPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPbox;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTbox;
    // End of variables declaration//GEN-END:variables
}
