/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fain;

import javax.swing.Box;

/**
 *
 * @author akshos
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        initComponents();
        createLogoutMenu();
    }

    private void createLogoutMenu(){
        javax.swing.JMenu logoutMenu = new javax.swing.JMenu();
        logoutMenu.setFont(new java.awt.Font("Dialog", 1, 14));
        logoutMenu.setText("Logout");
        logoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ((javax.swing.JMenu)evt.getSource()).setSelected(false);
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ((javax.swing.JMenu)evt.getSource()).setSelected(true);
            }
        });
        fainMainMenu.add(Box.createHorizontalGlue());
        fainMainMenu.add(logoutMenu);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDesktopPane = new javax.swing.JDesktopPane();
        fainMainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        aMasterMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        printingMenu = new javax.swing.JMenu();
        optionsMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainDesktopPane.setName("mainDesktopPane"); // NOI18N

        javax.swing.GroupLayout mainDesktopPaneLayout = new javax.swing.GroupLayout(mainDesktopPane);
        mainDesktopPane.setLayout(mainDesktopPaneLayout);
        mainDesktopPaneLayout.setHorizontalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainDesktopPaneLayout.setVerticalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(mainDesktopPane, java.awt.BorderLayout.CENTER);

        fainMainMenu.setName("fainMenuBar"); // NOI18N
        fainMainMenu.setPreferredSize(new java.awt.Dimension(240, 30));

        fileMenu.setText("Append");
        fileMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N
        fileMenu.setPreferredSize(new java.awt.Dimension(80, 21));
        fileMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fileMenuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fileMenuMouseEntered(evt);
            }
        });

        aMasterMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aMasterMenuItem.setText("Master");
        aMasterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMasterMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(aMasterMenuItem);

        jMenuItem2.setText("jMenuItem2");
        fileMenu.add(jMenuItem2);

        fainMainMenu.add(fileMenu);

        editMenu.setText("Edit");
        editMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        editMenu.setPreferredSize(new java.awt.Dimension(50, 21));
        editMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMenuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMenuMouseEntered(evt);
            }
        });
        fainMainMenu.add(editMenu);

        printingMenu.setText("Printing");
        printingMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        printingMenu.setPreferredSize(new java.awt.Dimension(80, 21));
        printingMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printingMenuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printingMenuMouseEntered(evt);
            }
        });
        fainMainMenu.add(printingMenu);

        optionsMenu.setText("Options");
        optionsMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        optionsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionsMenuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionsMenuMouseEntered(evt);
            }
        });
        fainMainMenu.add(optionsMenu);

        setJMenuBar(fainMainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMenuMouseEntered
        ((javax.swing.JMenu)evt.getSource()).setSelected(true);
    }//GEN-LAST:event_fileMenuMouseEntered

    private void fileMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMenuMouseExited
        ((javax.swing.JMenu)evt.getSource()).setSelected(false);
    }//GEN-LAST:event_fileMenuMouseExited

    private void editMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuMouseEntered
        ((javax.swing.JMenu)evt.getSource()).setSelected(true);
    }//GEN-LAST:event_editMenuMouseEntered

    private void editMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuMouseExited
        ((javax.swing.JMenu)evt.getSource()).setSelected(false);
    }//GEN-LAST:event_editMenuMouseExited

    private void printingMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printingMenuMouseEntered
        ((javax.swing.JMenu)evt.getSource()).setSelected(true);
    }//GEN-LAST:event_printingMenuMouseEntered

    private void printingMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printingMenuMouseExited
        ((javax.swing.JMenu)evt.getSource()).setSelected(false);
    }//GEN-LAST:event_printingMenuMouseExited

    private void optionsMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionsMenuMouseEntered
        ((javax.swing.JMenu)evt.getSource()).setSelected(true);
    }//GEN-LAST:event_optionsMenuMouseEntered

    private void optionsMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionsMenuMouseExited
        ((javax.swing.JMenu)evt.getSource()).setSelected(false);
    }//GEN-LAST:event_optionsMenuMouseExited

    private void aMasterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMasterMenuItemActionPerformed
        AMaster masterEntry = new AMaster();
        masterEntry.setSize(790, 300);
        addToMainDesktopPane(masterEntry);
    }//GEN-LAST:event_aMasterMenuItemActionPerformed
    
    /**
     * @param item the internal frame to be added to desktop pane
     */
    private void addToMainDesktopPane(javax.swing.JInternalFrame item){
        item.setVisible(true);
        this.mainDesktopPane.add(item);
        this.mainDesktopPane.revalidate();
        this.mainDesktopPane.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aMasterMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuBar fainMainMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JDesktopPane mainDesktopPane;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenu printingMenu;
    // End of variables declaration//GEN-END:variables
}
