/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fain;

import java.awt.Dimension;
import javax.swing.Box;

/**
 *
 * @author akshos
 */
public class Main extends javax.swing.JFrame {
    javax.swing.JInternalFrame activeInternalFrame[];
    int level;
    /**
     * Creates new form Main
     */
    public Main() {
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        initComponents();
        createLogoutMenu();
        this.activeInternalFrame = new javax.swing.JInternalFrame[5];
        this.level = 0;
    }

    private void createLogoutMenu(){
        javax.swing.JMenu logoutMenu = new javax.swing.JMenu();
        logoutMenu.setFont(new java.awt.Font("Dialog", 1, 14));
        logoutMenu.setText("Logout");
        logoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ((javax.swing.JMenu)evt.getSource()).setSelected(false);
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ((javax.swing.JMenu)evt.getSource()).setSelected(true);
            }
        });
        fainMainMenu.add(Box.createHorizontalGlue());
        fainMainMenu.add(logoutMenu);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        mainDesktopPane = new javax.swing.JDesktopPane();
        fainMainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        aMasterMenuItem = new javax.swing.JMenuItem();
        aTransactionMenuItem = new javax.swing.JMenuItem();
        aStockMenuItem = new javax.swing.JMenuItem();
        aPurchaseLatexMenuItem = new javax.swing.JMenuItem();
        aPurchaseOthersMenuItem = new javax.swing.JMenuItem();
        aSalesLatexMenuItem = new javax.swing.JMenuItem();
        aConsumptionMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        eMasterMenuItem = new javax.swing.JMenuItem();
        printingMenu = new javax.swing.JMenu();
        optionsMenu = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainDesktopPane.setName("mainDesktopPane"); // NOI18N

        javax.swing.GroupLayout mainDesktopPaneLayout = new javax.swing.GroupLayout(mainDesktopPane);
        mainDesktopPane.setLayout(mainDesktopPaneLayout);
        mainDesktopPaneLayout.setHorizontalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainDesktopPaneLayout.setVerticalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(mainDesktopPane, java.awt.BorderLayout.CENTER);

        fainMainMenu.setName("fainMenuBar"); // NOI18N
        fainMainMenu.setPreferredSize(new java.awt.Dimension(240, 30));

        fileMenu.setText("Append");
        fileMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N
        fileMenu.setPreferredSize(new java.awt.Dimension(80, 21));
        fileMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fileMenuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fileMenuMouseEntered(evt);
            }
        });

        aMasterMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aMasterMenuItem.setText("Master");
        aMasterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMasterMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(aMasterMenuItem);

        aTransactionMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aTransactionMenuItem.setText("Transaction");
        aTransactionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTransactionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(aTransactionMenuItem);

        aStockMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aStockMenuItem.setText("Stock");
        aStockMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aStockMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(aStockMenuItem);

        aPurchaseLatexMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aPurchaseLatexMenuItem.setText("Purchase Latex");
        aPurchaseLatexMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPurchaseLatexMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(aPurchaseLatexMenuItem);

        aPurchaseOthersMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aPurchaseOthersMenuItem.setText("Purchase Others");
        aPurchaseOthersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPurchaseOthersMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(aPurchaseOthersMenuItem);

        aSalesLatexMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aSalesLatexMenuItem.setText("Sales Latex");
        aSalesLatexMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSalesLatexMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(aSalesLatexMenuItem);

        aConsumptionMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aConsumptionMenuItem.setText("Consumption");
        aConsumptionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aConsumptionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(aConsumptionMenuItem);

        fainMainMenu.add(fileMenu);

        editMenu.setText("Edit");
        editMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        editMenu.setPreferredSize(new java.awt.Dimension(50, 21));
        editMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMenuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMenuMouseEntered(evt);
            }
        });

        eMasterMenuItem.setText("Master");
        eMasterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMasterMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(eMasterMenuItem);

        fainMainMenu.add(editMenu);

        printingMenu.setText("Printing");
        printingMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        printingMenu.setPreferredSize(new java.awt.Dimension(80, 21));
        printingMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printingMenuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printingMenuMouseEntered(evt);
            }
        });
        fainMainMenu.add(printingMenu);

        optionsMenu.setText("Options");
        optionsMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        optionsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionsMenuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionsMenuMouseEntered(evt);
            }
        });
        fainMainMenu.add(optionsMenu);

        setJMenuBar(fainMainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMenuMouseEntered
        ((javax.swing.JMenu)evt.getSource()).setSelected(true);
    }//GEN-LAST:event_fileMenuMouseEntered

    private void fileMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMenuMouseExited
        ((javax.swing.JMenu)evt.getSource()).setSelected(false);
    }//GEN-LAST:event_fileMenuMouseExited

    private void editMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuMouseEntered
        ((javax.swing.JMenu)evt.getSource()).setSelected(true);
    }//GEN-LAST:event_editMenuMouseEntered

    private void editMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuMouseExited
        ((javax.swing.JMenu)evt.getSource()).setSelected(false);
    }//GEN-LAST:event_editMenuMouseExited

    private void printingMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printingMenuMouseEntered
        ((javax.swing.JMenu)evt.getSource()).setSelected(true);
    }//GEN-LAST:event_printingMenuMouseEntered

    private void printingMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printingMenuMouseExited
        ((javax.swing.JMenu)evt.getSource()).setSelected(false);
    }//GEN-LAST:event_printingMenuMouseExited

    private void optionsMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionsMenuMouseEntered
        ((javax.swing.JMenu)evt.getSource()).setSelected(true);
    }//GEN-LAST:event_optionsMenuMouseEntered

    private void optionsMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionsMenuMouseExited
        ((javax.swing.JMenu)evt.getSource()).setSelected(false);
    }//GEN-LAST:event_optionsMenuMouseExited

    private void aMasterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMasterMenuItemActionPerformed
        AMaster masterEntry = new AMaster();
        masterEntry.setSize(790, 300);
        addToMainDesktopPane(masterEntry, this.level);
    }//GEN-LAST:event_aMasterMenuItemActionPerformed

    private void eMasterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMasterMenuItemActionPerformed
        EMaster masterEdit = new EMaster();
        masterEdit.setSize(785, 470);
        addToMainDesktopPane(masterEdit, this.level);
    }//GEN-LAST:event_eMasterMenuItemActionPerformed

    private void aTransactionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTransactionMenuItemActionPerformed
        ATransaction transactionEntry = new ATransaction();
        transactionEntry.setSize(790, 310);
        addToMainDesktopPane(transactionEntry, this.level);
    }//GEN-LAST:event_aTransactionMenuItemActionPerformed

    private void aStockMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aStockMenuItemActionPerformed
        AStock stockEntry = new AStock();
        stockEntry.setSize(790, 360);
        addToMainDesktopPane(stockEntry, this.level);
    }//GEN-LAST:event_aStockMenuItemActionPerformed

    private void aPurchaseLatexMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPurchaseLatexMenuItemActionPerformed
        APLatex purchaseLatexEntry = new APLatex();
        purchaseLatexEntry.setSize(790, 450);
        addToMainDesktopPane(purchaseLatexEntry, this.level);
    }//GEN-LAST:event_aPurchaseLatexMenuItemActionPerformed

    private void aPurchaseOthersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPurchaseOthersMenuItemActionPerformed
        APOthers purchaseOthersEntry = new APOthers();
        purchaseOthersEntry.setSize(790, 410);
        addToMainDesktopPane(purchaseOthersEntry, this.level);
    }//GEN-LAST:event_aPurchaseOthersMenuItemActionPerformed

    private void aSalesLatexMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSalesLatexMenuItemActionPerformed
        ASLatex salesLatexEntry = new ASLatex();
        salesLatexEntry.setSize(790, 530);
        addToMainDesktopPane(salesLatexEntry, this.level);
    }//GEN-LAST:event_aSalesLatexMenuItemActionPerformed

    private void aConsumptionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aConsumptionMenuItemActionPerformed
        AConsumption consumptionEntry = new AConsumption();
        consumptionEntry.setSize(790, 380);
        addToMainDesktopPane(consumptionEntry, this.level);
    }//GEN-LAST:event_aConsumptionMenuItemActionPerformed
    
    /**
     * @param item the internal frame to be added to desktop pane
     */
    private void addToMainDesktopPane(javax.swing.JInternalFrame item, int level){
        if(this.activeInternalFrame[level] != null){
            this.activeInternalFrame[level].doDefaultCloseAction();
        }
        this.activeInternalFrame[level] = item;
        item.setVisible(true);
        Dimension desktopSize = this.mainDesktopPane.getSize();
        Dimension internalFrameSize = item.getSize();
        item.setLocation((int)(desktopSize.getWidth() - internalFrameSize.getWidth())/2, 
                (int)(desktopSize.getHeight() - internalFrameSize.getHeight())/2);
        this.mainDesktopPane.add(item);
        this.mainDesktopPane.revalidate();
        this.mainDesktopPane.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aConsumptionMenuItem;
    private javax.swing.JMenuItem aMasterMenuItem;
    private javax.swing.JMenuItem aPurchaseLatexMenuItem;
    private javax.swing.JMenuItem aPurchaseOthersMenuItem;
    private javax.swing.JMenuItem aSalesLatexMenuItem;
    private javax.swing.JMenuItem aStockMenuItem;
    private javax.swing.JMenuItem aTransactionMenuItem;
    private javax.swing.JMenuItem eMasterMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuBar fainMainMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JDesktopPane mainDesktopPane;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenu printingMenu;
    // End of variables declaration//GEN-END:variables
}
